package com.k00ntz.euler;

import java.util.ArrayList;
import java.util.Arrays;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
 * first 10 terms will be:
 * <p>
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * <p>
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
 * even-valued terms.
 */
public class EvenFibs {
    public static void main(String[] args) {
        EvenFibs evenFibs = new EvenFibs();
        System.out.println(evenFibs.sumOfEvenFibs(4_000_000)); //4613732
    }

    public long sumOfEvenFibs(int limit) {
        ArrayList<Integer> fiboList = generateFiboList(limit);
        return fiboList.stream().filter(x -> x % 2 == 0).reduce(0, Integer::sum);
    }


    private ArrayList<Integer> generateFiboList(int limit) {
        ArrayList<Integer> fiboList = new ArrayList<>(Arrays.asList(1, 1));
        int last = 1;
        int previous = 1;
        while (last < limit) {
            int newLast = last + previous;
            fiboList.add(last + previous);
            previous = last;
            last = newLast;
        }
        return fiboList;
    }
}
